### ISSUE TITLE
[ENHANCE] leveled dimensions

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#118]
bc of that discussion about dimensions on that netherrr post i suddenly got this idea for maybe a config option for dimensions only accesible after certain levels? and maybe be able to put dimensions in there yourself? idk if this is easy or not. BUt it would be a nice addition. :p

**Comment by Soyaro666** [comment]
do you mean Tardis Level? this kinda exists. on my last cross dimension test i weren't able to enter the Nether because I hadn't enough energy. I just started the Savegame so I had a maximum of 1000. If the Energy Limits may be configurable per Dimension your idea would be done (btw, nice thought)

**Comment by DarkholmeTenk** [comment]
config format
S:leveledDimensions:<dimID>|<level>,<dimID>|<level>,...
should do?

**Comment by FoxPotato** [comment]
can't you like have a few. like a line for level 5, a line for level 10 etc.

**Comment by FoxPotato** [comment]
or wait, did you have it that you could have a custom level. I think you do, my mistake :p

**Comment by DarkholmeTenk** [comment]
github removed my angle bracket stuff, that's better

**Comment by Soyaro666** [comment]
and the Level means what? the Tardis needs to have this Level or the Tardis needs an energy storage of that many skillpoints?

**Comment by DarkholmeTenk** [comment]
tardis needs to have that level

**Comment by Soyaro666** [comment]
imo the energy storage should have that level because of continuity. a Tardis on level 10 with no skillpoint in energy storage could enter more dimensions than a tardis on level 5 with all skill points in energy storage... imo, like I said...

**Comment by DarkholmeTenk** [comment]
hmmm... I could change it to be cost of entering dimension rather than level

**Comment by FoxPotato** [comment]
Btw, your leveling system. Wouldn't it get like kinda really hard to level up after a bit?

**Comment by DarkholmeTenk** [comment]
yes? Same applies to vanilla minecraft xp system :P

**Comment by FoxPotato** [comment]
Ok yeah true, but that one resets after you enchant something?
You should implement something to reset the xp thing on the TARDIS too

**Comment by Soyaro666** [comment]
that wouldn't work since you need to have a Tardis at level X to get feature Y (for example: Level 5 to see whats happening on the Tardis exterior walls). this means he had to rewrite part of the rewards too.

which wouldn't be so bad when I think further. a fifth "skill" named features that adds stuff that previously required a specific level. this would let skillpoints become more valuable which could be balanced by the frequence they're paid (1 per level, something I already had in mind as an enhancement suggestion). in the first moment it appears to be a lot of work but instead of reacting to the tardis level it could react to the feature level (just another variable in existing code maybe?) and would appear less random...
well, you may already get used to my way of thinking. give me the igniting spark, I can't resist to write complex concepts for it just to get them out of my mind... please stop me if I'm going too far ;-)

**Comment by FoxPotato** [comment]
Or after a certain level have the amount of xp needed the same, or make it rise a little slower. I quite like the fact that levelling up makes things appear.

And please for the love of god, stop with the blinking emoticon with a nose. Idk why but it's annoying the hell out of me ;-;

**Comment by DarkholmeTenk** [comment]
;-)

**Comment by FoxPotato** [comment]
It's just like you're really mocking me.

**Comment by DarkholmeTenk** [comment]
?

**Comment by FoxPotato** [comment]
that face, it's just so. argh.
anyhow, it's not relevant to the post xD

**Comment by Soyaro666** [comment]
he meaned my ;-) thing. sorry, it's my habit to give most emoticons a nose. no special meaning behind that. actually i'm feeling about emoticons without a nose as confused as you are feeling about my...

jep, it's funny to have stuff that appeares with a levelup. it's been confusing at first. later it's been confusing to be the only one who can see that stuff. in multiplayer, in my tardis, my other test-player weren't able to see the new features. is this supposed to work that way or is it a bug (maybe with LAN servers where i've noticed that)?

**Comment by DarkholmeTenk** [comment]
It's a bug if the other player can't see the new features; it suggests that the other player isn't receiving any updates from the server.

**Comment by Soyaro666** [comment]
and its added to my list of things that needs to be reproduced
