### ISSUE TITLE
9minecraft arseiness warning

### ISSUE THREAD

**Issue by DarkholmeTenk** [DarkholmeTenk/TardisModIssues#120]
Add a warning which says "If you downloaded this from 9minecraft or a similar ad-walled site, you should know that they have breached the terms of my license by reposting my mod behind an ad-wall without permission" with a config option to disable for modpack creators.

**Comment by FoxPotato** [comment]
Please do, I hate those sites.
I literally got a virus once ._.

**Comment by DarkholmeTenk** [comment]
It'll be a warning that comes up every time you start a new world unless it's disabled in the configs probably.

**Comment by FoxPotato** [comment]
That works too

**Comment by Valiec** [comment]
Suggestion to reduce annoyance:

Trigger the warning only on the copy that 9minecraft steals by using Cuchaz's valid-jar-ID-list idea.

Go here for more info: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/2314237-list-of-sites-stealing-minecraft-content?comment=1083

I know I say to get it added to Forge there, but you could also add it to your mod directly. It's quite simple to code it I think (no harder than a version checker really).

Note: I mean to use this to trigger the alert, which can still be disabled in the config. However, if the jar ID checks out as valid once, it should automatically disable the alert in the config. Because of this, you can use a single ID per version without much disruption to users (since if they downloaded and ran the build before it was stolen, the alert is already disabled for them).

**Comment by DarkholmeTenk** [comment]
it'd require me to build something like a version checker and be constantly policing it
