### ISSUE TITLE
[ENHANCE] LIFT

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#125]
Maybe have it so that lifts are able to have multiple floors. So a lift at the bottom, a few blocks up a forcefield and then another few blocks up another forcefield, and then if you're on the first forcefield and you jump you go up to the second one.

**Comment by Soyaro666** [comment]
I really enjoy to see another one thinking like me. This enhancement would allow to create new Lift rooms. up and down in one, 2 up, 2 down, each in normal and further versions - or a modular lift system that would be another suggestion I was thinking about - I should wait for Darkholme to give a statement to your enhancement before designing addons for it, shouldn't I? ^^

**Comment by FoxPotato** [comment]
You could wait, but with more detailed suggestions there's a bigger chance something will be added ;p

**Comment by Soyaro666** [comment]
well, you get what you ask for.
the Lift-System could be replaced by a modular system. maybe based on normal corridors? in it's center could be a lift block both in the floor and the roof. if you spawn another normal corridor on those lift blocks it could "transform" into a lift in that direction. the real enhancement of this would be the ability to repeat that - you would be able to stack multiple lifts above or underneath each other. this would allow to build big lift shafts instead of the stairs of lifts we currently have to build. since there is a limitation in the Lift mechanics (a max of 64 blocks they can push you up I think?) and every part would be as high as the lifts are right now (which are 10 blocks if I remember right) you could build 6 floors with one lift, then another lift shaft must be built.
well, I can't think of the usage of 6 floors right now but I'd like to have 1 lift instead of 2 to connect the 3 floors I'm currently using

**Comment by Soyaro666** [comment]
thought further. now I'm thinking about removing the junctions too and making the Tardis even more flexible.
think about a room of 5x5x5 blocks, so it's 3x3x3 on the inside. every wall, even roof and floor, are doors. you could build a tiny corridor down to create some space for the craftable lift block (or any other block that can do it's job; thaumcraft levitators maybe?) and build a small corridor up to build a Lift with another door on top for another of these junction rooms or another corridor maybe. I guess it would be useful if forcefields would spawn automatically in doors that opened down. of course, if the walls of this 5³-room are doors the controller block would need to be placed somewhere in the edge around the bottom door but that shouldn't be a problem...

I guess this changes (including my above post) would be that much work that I could understand if these ideas get refused but I hope to give some useful ideas for own improvements.

**Comment by FoxPotato** [comment]
Or ya know. keep junctions because they're actually useful and what you're suggesting sounds kinda weird. (In my opinion)

**Comment by Soyaro666** [comment]
what I suggest is one room that can be used to build every other junction so I would remove my Problem of "which one do I need now", because I don#t have to dismantle and replace it later if I need more corridors from that junction than I previously thought...

**Comment by FoxPotato** [comment]
But that would make corridors.... organized D:
The tardis should be a mess. I mean, in the show. alot of the same corridors could lead to the same doorway, 1 doorway could also lead to multiple corrdiros depending what way you walk through it. and 5x5 cubes would be ugly.

**Comment by Soyaro666** [comment]
that's the actual size of a corridor (well, they are longer, but you know. 5 blocks wide, 5 blocks high). in fact I'm just requesting a shorter version of the four way junction...

**Comment by laz2727** [comment]
Tbh, in show Tardis feels random-generated and with little respect for
Euclid.

In fact, something non-euclidian would work great, but be very hard to make
in Minecraft. Possible, but hard.

2015-05-20 22:37 GMT+06:00 Soyaro666 <notifications@github.com>:

**Comment by FoxPotato** [comment]
Just make a shorter version yourself. no biggie.

**Comment by Soyaro666** [comment]
FoxPotato: I would if I would know how. I didn't search for any information about it yet. maybe I'll do later...

laz2727: it would be funny to have some... lets say strange experiences... I'd suggest to port players without a key randomly between identical rooms. since the normal corridor and the 4 way junctions are very common in my Tardis my players would be driven crazy by appearing in sections they never even wanted to see. but as you said it would be very hard to get that to work so I wouldn't really think it would ever be implemented...

**Comment by FoxPotato** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod?page=4#c75

use this guide and then if you want you can post the schematics to minecraftforum, with screenshots ofc (:
