### ISSUE TITLE
[BUG] Lifts

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#136]
When placing 4 lifts in a 3x3 cube like this:
l a l
aaa
l a l
a = air      l = lift

and when you go down from the forcefield above it, you get stuck for a bit. slow movement, not being able to jump.
This is quite annoying tbh.

**Comment by FoxPotato** [comment]
Also, just a lift with a 3x3 slab cover

**Comment by Soyaro666** [comment]
I didn't test the craftable lifts yet but I had similar experience with the lift rooms in my Tardis. In my experience it does appear most when I'm above multiple blocks (above a corner for example) and/or try to "walk" while flying down.
In addition I sometimes can't take the last half block to stand on a forcefield so i drift back down (with a further lift that I want to go up this is really annoying). this seems to be related since it too appears only while I'm above the corner of a lift block or while I'm "walking" while flying up.

btw: didnt have this problems since build 107 but didn't play a lot since then too. don't know if they are still possible. but since they seem to be related to FoxPotatos problem I thought I should write about it.

**Comment by FoxPotato** [comment]
I noticed looking up helps, and holding space.
and it's not because of walking, i think my problem was that some lifts were trying to push me up and other trying to pull me down.

**Comment by DarkholmeTenk** [comment]
Think lifts are pretty much fixed. Dunno about lifts with overlapping bounds, but they shouldn't be necessary now the multiple floor lifts are implemented.
