### ISSUE TITLE
[ENHANCE] Distance gauge

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#145]
I'd love a way to check how close the TARDIS is to landing, or to its destinations (which is actually teh same thing now i think about it)
I'm flying pretty far and I have to keep landing to check how close I am.

**Comment by TARDIS2016** [comment]
where are you trying to go?

**Comment by FoxPotato** [comment]
The end of the universe.

**Comment by TARDIS2016** [comment]
Is that even possible in minecraft?

**Comment by FoxPotato** [comment]
One way to find out

**Comment by Soyaro666** [comment]
in past there existed a bug in minecraft. I guess it's called the outer lands. there, because of a buggy algorythm, the world generator messed up everything. if I remember right you needed to run straight forward for multiple reallife days to reach it. well, that got fixed month ago (maybe years? I'm not sure). there existed mods that did bring that region back but without them minecraft has only one End (the dimension, you know)

**Comment by FoxPotato** [comment]
The end of the universe is still there. It's an invisible wall with like a ghost version of terrain generation behind it.
