### ISSUE TITLE
[ENHANCE] Timelord Trenchcoat

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#203]
a craftable coat that when equiped grants access to 2 extra inventory slots that can hold a tardis key and the sonic. the inventory of the coat would be like the vanilla enderchest in that it is persistant and per player. craftable with a leather chestplate and a cronotron crystal. that way if the player dies and loses their items they have 2 options for tardis recovory. doing so without a gui ofcoarse :P

**Comment by Soyaro666** [comment]
like adding 2 slots to your quick slot bar. I would suggest to use a screwdriver and a key with any chest in lab so wearing that chest adds the slots. Maybe that Chest could be linked to whoever wears it first so only that Person can see the additional slots while the items in those slots act like they did before crafting the chest.

**Comment by FoxPotato** [comment]
Yeah but, what ya'll are suggesting, wouldn't that be editing a GUI?

**Comment by DarkholmeTenk** [comment]
https://www.youtube.com/watch?v=znGBU5oODz8

**Comment by FoxPotato** [comment]
I guess that confirms it

**Comment by Soyaro666** [comment]
well, the part about aditional slots in your quick bar would be editing a gui, that's true. I suggested it that way because I can't think of another way to implement the feature @AlienXtream suggested. at least it's not adding an own GUI...
Any ideas how to achieve the same result without the additional GUI elements?

**Comment by AlienXtream** [comment]
hotkeys?

**Comment by DarkholmeTenk** [comment]
Too many mods add hotkeys; there's only so many buttons on a keyboard and I don't want to take any of them.

Modifying a vanilla gui is even more annoying than adding a gui. Not only that, but the amount of mods which add alternative inventory guis is silly and awkward.

I'd rather just work out how to make the screwdriver soulbound :P

**Comment by Soyaro666** [comment]
hmmm... jump+rightclick to access screwdriver-slot (get screwdriver from Coat), jump+shift+rightclick to access key-slot (get key from coat), jump+rightclick with one of these items in hand to place it in its slot. these aren't available until you wear a timelord chestplate that is linked to you. no GUI needed, items can't be stolen by others. only negative point: you had to check your pockets like in reallife ^^
crafting recipe could simply be any chestplate in lab. maybe this is doable to check if item can be worn in chestplate slot to make it mod-compatible?

thought about combinations with jumping because shift+rightclick can't be used with screwdriver, it already has a function on that combination. that's the reason why I suggested shift for key-slot instead of screwdriver slot too. at least we will access the screwdriver-slot more often so it makes sense to have an easier combination there

**Comment by FoxPotato** [comment]
ok but what if i'm on the edge of a block and i need to acces my sonic. But if I jump I'll die. I don't think jumping to acces the things is gonna work. And jump right click puts away items but also gets you the sonic, but not the key. The idea could've worked with adding slots to the default GUI but I think a soulbound sonic screwdriver would be easier to handle than what this idea has become.

**Comment by Soyaro666** [comment]
I can't figure out a situation where you die if you jump. And I can't figure out what you would need your sonic for if you're in such a situation... But yes, you may need your key in a dangerous situation...
I thought about needing to have your screwdriver in hand to put it away. and of course you would need to click into empty space, not on a block (in that case other things may want to do stuff)...
I did write that concept because I wanted to come up with an idea that would work without a GUI. At least nobody has to use it. You simply don't need to wear a chestplate with timelord modifications (if it will ever exist)

**Comment by liftoff** [comment]
How about instead of dying players holding a sonic screwdriver simply get paralyzed for a few seconds before giving off a TNT-like explosion (throwing mobs and other players a distance away) after which their skin gets a permanent, random change? :grinning: 

"Oh no, I'm dying!  I'm about to regenerate!"
**`<BOOM!>`**
"Long hair?  I'm a girl?!?"

**Comment by Soyaro666** [comment]
funny idea but there could be some trouble...
At first there already is a mechanic to teleport you into tardis instead of letting you die (you need to be "near" the tardis. I guess it has a range of 5 or less chunks. and maybe the tardis needs to have a high enough level to unlock transmat - didn't try it out yet, for my survival savegames it's working since I first needed it ^^). I guess that's Darks way of implementing regeneration.
Then there whould possibly be problems with changing player skins. I know DalekMod can do it but because the skin usually is downloaded from minecraft servers it would be a lot of work I think.
A Timelord usually has energy for 12 regenerations so after your 13th death it would restart (which would be annoying in some way) unless you're playing in hardcore mode (which this would be supposed for I guess, propably with tardis key in starting inventory?)
And after regeneration a timelord has highly increased healing abilities for himself and others (the doctor lost a hand which grew in moments, river cured a broken bone by laying her hands on it).

Don't misunderstand me. I like the idea (well, most of it - the changing skin part would be a little annoying for me) but implementing it would be a lot of work. so even if Darkholme decides to implement it even partially I wouldn't expect it any time soon.

**Comment by DanNetwalker** [comment]
Ok, the change to the skin... I could see it as a feature like you config several skins for your player; by doing something a little more special than dying you "regenerate" into one of the configured skins. IF at all possible... I know there was a "wardrobe" mod that let you change your skin, but that was before the new skin server.

But the coat inventory... would it be possible to press "Shift + Normal Inventory key" to access it?

**Comment by Soyaro666** [comment]
I guess you're talking about adding a GUI for coat inventory? according to Darkholme GUI's aren't worth a though, they're refused without exception...

**Comment by FoxPotato** [comment]
1, GUI's are probably not gonna happen. and 2. regeneration is probably not gonna happen. it's more doctor who than just TARDIS.

**Comment by ghost** [comment]
FoxPotato, dark never ever say "no" for regeneration, why you hate it so? it's not more Doctor Who, it is more Timelord.

**Comment by FoxPotato** [comment]
Assuming that neither the trenchcoat or regeneration will happen I will close this issue.
