### ISSUE TITLE
[ENHANCE] Use gamerule for setting time and keeping time

### ISSUE THREAD

**Issue by mrammy** [DarkholmeTenk/TardisModIssues#250]
As opposed to constantly setting the time to midnight or noon. Simply set the time once and turn the gamerule for doDaylightCycle in the tardis dimension to false.

**Comment by ruifung** [comment]
heck, allow it to have a daylight cycle too. Or alternatively have a option to match the time of the tardis exterior =P

**Comment by handicraftsman** [comment]
Other players can be online.

**Comment by ruifung** [comment]
?

**Comment by DarkholmeTenk** [comment]
The time isn't constantly set to midnight or noon, that's not how minecraft works; there is a function which returns the time in the world currently and that either returns noon or midnight.
There is a slight amount of variance in the time (approx 1s) because there was a bug with hunger overhaul caused by having a fixed time.

**Comment by mrammy** [comment]
I see.
