### ISSUE TITLE
[Enhance]Add a command to completely reset somebody's TARDIS

### ISSUE THREAD

**Issue by XxRagingKillerX** [DarkholmeTenk/TardisModIssues#292]
want to fix issue on my server with me and my friends please maybe make a command /tardisreset name would be helpful

**Comment by DarkholmeTenk** [comment]
/trep total [worldID] [Owner]
will clear out the interior, but it won't reset the data store so :P

**Comment by XxRagingKillerX** [comment]
ok this is what is happerning when i try spawn a  new tardis in it say already owns a tardis and dont let me reset or get it back and it kinda annoying we have trayed reseting the playerdata 1 by 1 and it still dont work

**Comment by XxRagingKillerX** [comment]
ok this is what is happerning when i try spawn a  new tardis in it say already owns a tardis and dont let me reset or get it back and it kinda annoying we have trayed reseting the playerdata 1 by 1 and it still dont work please respond with a fix even with that command it didnt fix / return it back as it says i have one but i dont ??
 and later this night i got this crash report to http://pastebin.com/auCKi279

**Comment by XxRagingKillerX** [comment]
and now server wont reopen

**Comment by DarkholmeTenk** [comment]
Looks like you somehow deleted the TDS for an existing world.
If the server won't start, turn on forge's delete erroring tile entities to get the server to start (then save and turn it back off again), find out which world doesn't have a core by using "/ttp [worldID] 0 60 0" to teleport to each world in turn, then delete that world from the registry by doing "/treg list" to find out who the world belongs to and "/treg remove [playerName]" to remove that mapping and then never go near that dimension again.

As an addendum: No data is stored in the player's data. The player<->dimension mapping is stored in the overworld's data (TModPReg.dat and TDimReg.dat specifically), because it's much simpler to use world data than player data. Please do not just go deleting stuff, it causes bad things.

**Comment by XxRagingKillerX** [comment]
so how do i fix the tardis and get one  as it says i have one but i dont

**Comment by DarkholmeTenk** [comment]
delete the dimension and do /treg remove [playerName]

**Comment by XxRagingKillerX** [comment]
how does the tardis shields work

**Comment by DarkholmeTenk** [comment]
If you're on the DamageSystem builds then they are affected by incoming damage before the hull is. If you're not, then they do nothing :P

**Comment by XxRagingKillerX** [comment]
ok thanks

**Comment by XxRagingKillerX** [comment]
one little joke thing that would be cool in the tv show they talk about a pool in the library like a book library that would be a epic room to have lol

**Comment by DarkholmeTenk** [comment]
`/treg remove total PlayerName` will remove everything in their tardis and remove it from the list of tardises and will unregister the dimension if it's registered as a tardis.
