### ISSUE TITLE
[ENHANCE] recoloring limits/pattern change

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#312]
make block coloring restricted to schemas ("paint" dosnt flow out of the room your in) and change the pattern to a square area to make it more predictable

**Comment by FoxPotato** [comment]
Iirc, the code literally just checks if the surrounding blocks are of the same id and colours them, and repeats this for a few times. So this would probably require Dark to rewrite the code.

But I have to agree, having the pattern change to something less random would be nice.

**Comment by AlienXtream** [comment]
well i was actually talking to dark about this and he told me to make an "issue". he said possibly but no guarantees so :)

**Comment by DarkholmeTenk** [comment]
But the beauty of darkcores block iterator is that all I'd have to do is write a new validator.

**Comment by FoxPotato** [comment]
welp, my mistake. The last time I saw the code I didn't really understand it :p

**Comment by Validfire** [comment]
The way I'm understanding this is, even if someone created a schema coloured all black, and someone spawns it, it will be all white?

As a designer, I disagree with this idea, as my first schema set was an extension pack for the Tenthish Console added in that update. I loved having all of my rooms match my Console room, that's why I make my Schematics in sets... To keep things looking nice. If you must insert this, at least add a configuration option for those who don't agree.

**Comment by DarkholmeTenk** [comment]
No, this idea is more when you repaint an area (i.e. right click a block twice), the painting will stay inside the current room.

**Comment by Validfire** [comment]
OK, the way it was explained confused me. Thanks for clearing things up.

**Comment by AlienXtream** [comment]
yeh... i get that a lot :/
