### ISSUE TITLE
Sonic Screwdriver Broken

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#313]
I am not sure if other are experiencing anything like this but after saving and exiting my game to later come back I find the screwdriver stuck on reconfigure mode. I tried both updating the game and darkcore to the updated version and resetting the config files but it the screwdriver is still stuck. Is there another way to allow the screwdriver to change modes or fix this problem?

**Comment by AlienXtream** [comment]
did you try getting a new sonic from the console? it sounds like (to me) that the sonic has unbound from your player. getting it from nei/creative mode MIGHT also cause this if you spawned it in that way (i say might cos im not 100% sure)

**Comment by DarkholmeTenk** [comment]
Which version are you using?
Does getting a new screwdriver fix things?
Was anything printed to the console?
Can you right click with other things, because hunger overhaul had a known bug which caused right clicks not to work, which I fixed progwml6/HungerOverhaul@2af56ade10082a536e36d4cdc279c115c2964ba9

**Comment by ghost** [comment]
I managed to fix the problem it was actually a keyboard mapping problem and I do not use the same keys in minecraft for anything else so it was hard to notice until yesterday. Sorry about that.
