### ISSUE TITLE
[ENHANCE]Tardis Computer/Keyboard

### ISSUE THREAD

**Issue by MaxBernstein** [DarkholmeTenk/TardisModIssues#376]
So... Adjusting the coordinates by hand it's a bit... Pain the neck sometimes, and the Tardis isn't 100% accuracy (sometimes my tardis land a few metters to the left sometimes a few kilometers...) So, I have an idea, what about in some level, like level 20 or 30 (Yes, high!) The Tardis got 100% accuracy and add an option to insert, typing the coordinates, if it is overworld, if it need to land, etc. Like an Tardis Interface. But It's need to be on high level because it's OP and It's cool to mess around with the levers and buttons, but sometimes is a pain the neck xP
Well, that's it, thanks!

**Comment by DarkholmeTenk** [comment]
At level 15 (configurable in new versions), the tardis does gain 100% accuracy, assuming you don't introduce instability by missing the blue buttons. The reason the TARDIS will land a few meters in a particular direction is either because you would have landed inside a block and it found a nearby safe location or you added instability. There's no way you landed a few thousand blocks away from where the screen said you would land.

I'm not going to add an easy way to insert coordinates because I think the levers are the most interesting thing about this tardis and it's what differentiates it from the dalek mod tardis, etc. If you have areas you visit often and want an easier way to get there, that's what the bookmarks are for.
