### ISSUE TITLE
at tardis.common.tileents.ConsoleTileEntity.getDimFromControl(ConsoleTileEntity. 109-DS

### ISSUE THREAD

**Issue by ProsperCraft** [DarkholmeTenk/TardisModIssues#378]
http://pastebin.com/R8UAJkm7

When double clicking the drift button.

Able to reproduce.

**Comment by ProsperCraft** [comment]
Reproduced here - http://paste.ee/p/y80PL

**Comment by DarkholmeTenk** [comment]
Nooooooooope. Not accepting this. That can't happen. What have you done?

``` java
    private int getDimFromControl(int dCont)
    {
        TardisDataStore ds = Helper.getDataStore(this);
        if(ds != null)
            return TardisMod.otherDims.getDimFromControl(dCont,ds.getLevel());
        return 0;
    }
```

line 910 is the return statement. otherDims can't be null, it's initialised on server start. dCont is an int, can't be null, ds can't be null because we just checked for that. ds.getLevel() returns an int, that can't be null.
getDimFromControl returns an Integer which can be null and would cause an NPE, except...

``` java
    public Integer getDimFromControl(int control, int level)
    {
        if (ServerHelper.isClient()) return 0;
        List<Integer> dims = getDims(level);
        int index = MathHelper.clamp(control, 0, dims.size() - 1);
        int dim = dims.get(index);
        return dim;
    }
```

it only returns 0, which is fine or dim which is an int and therefore cannot be null. If dims.get returned null, it would cause an NPE in this line of code not in the CTE.

Therefore I can only conclude that clearly a dark sorceror is at work here and has hexed your server.

**Comment by DarkholmeTenk** [comment]
Added a bunch of null checks for nulls that can't exist...

**Comment by ghost** [comment]
I do know that this is closed but isn't sharing caring. I have the same problem here too.
