### ISSUE TITLE
[BUG] Max Rooms = 0  bugs

### ISSUE THREAD

**Issue by mille449** [DarkholmeTenk/TardisModIssues#390]
When "Max rooms" is set to zero, the speed always shows NaN.

Also, while it may not be a bug per say, when "Max rooms increase"  is set to zero, the upgrade console still allows points to be allocated to additional rooms despite the fact that it won't actually give any additional rooms. It would be nice if this upgrade was prevented.

**Comment by DarkholmeTenk** [comment]
Setting either to 0 is essentially not a valid input, same as if you put -1. It shows NaN because it does rooms/maxRooms in the speed calculation, if maxRooms is 0, that isn't valid.
I'll add some code to make it so the min has to be 1.
The best option to disable room building would be for you to remake all the console rooms and make the primary doors inaccessible, but it makes the point of every tardis being its own dimension kinda pointless :P.

**Comment by mille449** [comment]
I figured it was doing something like that.  Basically, i want to let players use the tardis for transport and a small base (anything that can fit in the main room), but I don't want them spending their entire life in the tardis, never having to fight mobs, nor abusing the always day mechanic for solar panels.  Ya, it defeats the purpose of the tardis being in its own dimension, but I would like the option to do so.
