### ISSUE TITLE
Enhance  AE2 wireless  

### ISSUE THREAD

**Issue by SomeBadGamer** [DarkholmeTenk/TardisModIssues#417]
I think if you have a wireless  signal in the tardis connected  to a ae2 roundle the signal should carry to the extirior  because it is annoying  going in and out just for forgetting  one item

**Comment by Entoarox** [comment]
I would prefer a engine upgrade that allows for short-range (Say 16 blocks) around the tardis exterior to have a wireless signal irrelevant of if you are running wireless inside the tardis.

**Comment by SomeBadGamer** [comment]
That dose sound more balanced so would it get damaged  every time a signal is used or should it not brake?

**Comment by Entoarox** [comment]
I dont see any reason for it to become damaged, since a short-range wireless AE wouldnt be a massive advantage (Often-visited areas are likely to end up with landing pads that could easily have wireless emitters attached to them) and it would lock up a upgrade slot that could be put towards levels otherwise.

**Comment by SomeBadGamer** [comment]
The damage  was just a thogh but it should cost something  not just be free maby a constant 1 energy  drain per sec because you generate  more than one energy  easy but it is a good balance

**Comment by Entoarox** [comment]
It could just drain AE from your AE network the same as a normal wireless transmitter?

**Comment by SomeBadGamer** [comment]
That is hard in terms of coding  the exterior  is a funny thing for stuff like that but making it take artron  energy  will be easier  for dark to coee

**Comment by weldinclusion** [comment]
Why not build a landing pad and connect an AE interface to the roundel, then attach your access point?
I realize that would preclude moving it around as you travel but I don't see why the Tardis would be an emitter for a signal from another mod.

**Comment by Entoarox** [comment]
@weldinclusion For the same reason you can connect cables from other mods, to make the tardis a functional feature instead of a curiousity.
The upgrade based emitter should only be short-range, for those annoying - but common - "Dang, I forgot X" situations where going back into the tardis (And switching dimensions, something that not every PC can do quickly) can be offset with being able to use your wireless terminal to grab the missed items.

For common locations, yes you would likely have a landing pad with attached emitter, but that would also come with the ability to choose the range of the wireless, instead of the relatively tiny distance the upgrade would provide.

**Comment by weldinclusion** [comment]
I would hardly call the Tardis as it exists a mere curiosity.  I recognize the convenience of what you're asking for but I don't see how it fits with the theme of the mod.  I'd certainly use it if it gets added.

**Comment by DarkholmeTenk** [comment]
As far as I remember, the AE API does not provide a reasonable way to do this, whereas it does provide a relatively easy way to connect 2 blocks.

**Comment by ghost** [comment]
@DarkholmeTenk however, it is actualy a very good thing. I think you REALY MUST write API for yourself to transfer data throught dimensions around TARIDS because i have same thing with OpenComputers wireless terminal. I REALY think you need to do something like "Providing zone", that also can be on engine as control of radius and be enabled/disabled with interface interraction lever. Also, sometimes portable data-center is a good thing :D 
Think this is OP? No, because of #YOLO

**Comment by FoxPotato** [comment]
I agree with weldinclusion, the landing pad connecting with the TARDIS sounds like a much better idea.

**Comment by DarkholmeTenk** [comment]
I don't think I can easily add AE2 wireless and I definitely don't want to rewrite AE to add it.
