### ISSUE TITLE
[BUG] Can't control anything

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#434]
Hey Dark, 

after a server restart, with adding new mods, one of our Tardis is not controllable anymore.
The owner of it put much effort in designing the interior and so on.

Every lever or button on the control panel seems to be in "default" position, and cant be clicked anymore, also the panels under the controller, where u can repair the tardis etc. is like gone away. 

Is there a way to reset just the control room ? 

FYI if it helps, the mods added and or removed were:
- Ars Magica 2
- Aether II
- Power Converters

Also I changed the dimension blacklist, and i didn't knew that he was with his Tardis in one of the now blacklisted dimensions.
A Recall into the Overworld didn't fixed the Problem

Greetings 
TheRealHypo

**Comment by FoxPotato** [comment]
Have you tried going into creative and breaking the console and/or engine block? it should replace itself. maybe try and change the console layout, the option is on the engine. I mean it doesn't change the console block but it might do something. You never know.

**Comment by ghost** [comment]
Hey, I tried to click the Invisible Interior Change Button on the engine, but that didn't fixed the problem. 
As soon as the MC Session servers are back up running, I'll try breaking the console.

**Comment by Webber88** [comment]
ohto change the outer image of the tardis have the image upgrade in your hand and to change it right click(or shift right click) until its on the setting you want and use your tardis...

**Comment by Webber88** [comment]
just use the upgrade module(you may need to go intp creative)

**Comment by DarkholmeTenk** [comment]
Most interesting info is what's in your console when you try pressing buttons? both server and client side.

**Comment by ghost** [comment]
Waila shows no Controls while hovering. So there is nothing clickable anymore. Log doesn't say anything either.

**Comment by FoxPotato** [comment]
Is it happening to any other TARDISes? Maybe try opening the world in singleplayer or something?
I don't think this bug has happened before.

**Comment by ghost** [comment]
./trepair (tardis owner) or (id) i'm not sure
else, /trepair total

**Comment by DarkholmeTenk** [comment]
Have you somehow moved the blocks out of their regular position or something? Waila not showing anything and nothing being printed at all on a right click suggests the TE isn't responding correctly. What version of darkcore and tardismod are you using?

**Comment by DarkholmeTenk** [comment]
Scratch that, you added aether 2, bet you aether 2 is configured to use the same dimension id that person's tardis occupies.

**Comment by ghost** [comment]
Yeah, the dimension ID was overwritten by aether, but after backup
before the aether, changing the IDs for it and restarting, it didn't
recognize me either.
So dunno what happened there. I didn't knew that there was a "/trepair"
command.
Maybe a overview of all commands in the forum or in game manual would be
nice.

I'm using the version u named me after mentioning the unstabilized flight
bug.

We fixed the problem for ourselves with deleting the old tardis and
matching the player with a new tardis dimension.
Seemed to be the fastest way he could use it again.

Am Sonntag, 7. Februar 2016 schrieb DarkholmeTenk :

**Comment by AlienXtream** [comment]
not a dim thing
![2016-02-12_17 28 19](https://cloud.githubusercontent.com/assets/12606809/13000414/201d4ca0-d1ae-11e5-9dee-000db0d4f26b.png)
happens on creating tardis or entering existing one

**Comment by DarkholmeTenk** [comment]
I can't think of any other reason why the TDS wouldn't exist for a world.

**Comment by AlienXtream** [comment]
ok so i found the problem mod in my setup. http://minecraft.curseforge.com/projects/dynamic-surroundings was causing the issue. thing is.... its exclusively client side?!

**Comment by FoxPotato** [comment]
Controls are rendered client side iirc. were you able to click them? Maybe change the level of debug text in the config and see if the hits are registring.

**Comment by AlienXtream** [comment]
will take a look but the chat printing isnt working (thats not rendering related so shouldnt be affected in theory right?)

**Comment by FoxPotato** [comment]
Everything in the game has to be rendered at some point, so i assume the chat has to be too.
Also, does everything work correctly in the vanilla dimensions?

**Comment by AlienXtream** [comment]
overworld for sure. everything "works" but the console (and engine) of the tardis. i see what you are getting at with the chat thing but it works fine for everything else (messaging, commands etc....) so if dark is just sending a message to chat there is no rendering involved on the part of the tardis in that aspect. there is no output on interacting with the tardis console in the MC console.

**Comment by AlienXtream** [comment]
at this point im not interested in a workaround (i can just remove the mod, its a sound mod mainly) i wana use the fact that i have a "reliable" way to reproduce this bug to help get to to the root of the issue and solve it for (hopefuly) all cases. dosnt the aether mod add in custom rendering? that could explain the otherwise unrelated mods doing the same thing

**Comment by FoxPotato** [comment]
You say messaging and commands work fine. in what way? Did you perhaps hide chat in multiplayer settings? Or if you mean the TARDIS doesnt send the usual chat messages, that's probably bc the controls don't get called because the hits aren't being registered.
And debug text gets printed in the console, so check your logs.

And if the overworld worked fine i would assume it's something in the WorldProvider since that, iirc, renders all the particles and players and such.

**Comment by AlienXtream** [comment]
i can use chat chat (SP) and there is nothing in console, i was watching it (duel monitors). from what i understand its basicly that ambient sound mod (matmos or something) revived for forge. i am running an official back port of the mod as its really for 1.8.9. i would assume it only gets info from the dim providers for ambient sounds (nether/end exclusive ambiance). unless a mod spesificly uses custom fog distances (like thaumcraft) then no i can only assume it wouldnt.

**Comment by FoxPotato** [comment]
"As a player moves to higher elevations it gets a little bit hazy. Haze increases with elevation as well as rain intensity.

These atmospheric effects only happen if the dimension has a sky. This means it doesn’t apply to The Nether or The End.

Firejets randomly spawn on top of lava source blocks.  These jets spew fire or lava spark particle effects.

Bubblejets randomly spawn at the bottom of oceans and lakes.

Biome fog - some biomes are configured to have background fog that obscure vision."
It doesn't just use sound. Still confused as to why it doesn't register the hits tho.

**Comment by FoxPotato** [comment]
Also, this seems to be a different problem than the first one. Maybe start a new issue, so that this one can be closed. (Or closed after the commands have been cleared up a tad bit :P)

**Comment by AlienXtream** [comment]
ok, and i have the elevation haze off so thats not it :P

**Comment by OreCruncher** [comment]
Set "Fancy Cloud Handling" to false in the dsurround.cfg file.  Fixed it for me.

A bit of an explanation....

Fancy cloud rendering does two things: modifies the fog color value for rendering, and modifies the cloud color value for rendering.  To accomplish this Dynamic Surroundings puts a [WorldProvider "shim"](https://github.com/OreCruncher/BetterRain/blob/master/src/main/java/org/blockartistry/mod/DynSurround/client/WorldProviderShim.java)  between the World instance and it's WorldProvider instance.  Operationally, the shim forwards almost all requests to the original WorldProvider, just that in the case of cloud/fog color handling it does some extra manipulations to the resulting value.

I would like to take a look at the WorldProvider code for the Tardis dimension to see where things can be improved.

**Comment by FoxPotato** [comment]
You would have to get permission from Dark, I am not allowed to show any of the source code I'm afraid.
If you could tell me what you think the problem might be I could take a look at it. 
I know it's just a WorldProvider, but it's not up to me to decide :P

**Comment by OreCruncher** [comment]
That's just it - not sure exactly what I am looking for, but I am thinking it is somehow related to the bidirectional reference between the world and provider (world has a reference to provider, provider has a reference to world).  You can take a look at my shim code for 1.7.10 [here](https://github.com/OreCruncher/BetterRain/blob/1.7.10/src/main/java/org/blockartistry/mod/DynSurround/client/WorldProviderShim.java).

**Comment by FoxPotato** [comment]
Could it possibly be because multiple worlds use the same provider? Every TARDIS has it's own dimension and thus it's own instance of the provider.
But the current WorldProvider is fairly standard, it just sets the celestial angle to either 0 or 0.5 depending on a button. And in updateWeather it sets everything to 0.

Also, just wondering. Why aren't there any Overrides in the WorldProviderShim?

**Comment by OreCruncher** [comment]
My logic places the shim during world load.  That logic is [here](https://github.com/OreCruncher/BetterRain/blob/1.7.10/src/main/java/org/blockartistry/mod/DynSurround/client/ClientEffectHandler.java#L111).

As for Override, Java doesn't necessarily need it.  It assumes override as a default.  Generally, though, using Override is good practice because if a signature does not exist in any of the base classes Java will complain about it.  It helps prevent stupid coding issues.  The reason it specifically doesn't exist in this code is because I copied/pasted what the Minecraft WorldProvider had and edited from there.

**Comment by FoxPotato** [comment]
I thought i might've found something with the overrides, but it's never the easiest solution is it :P 
I'm just gonna go through the source and check where the controls and WorldProvider talk to each other.

**Comment by OreCruncher** [comment]
I wouldn't spend too much time on it.  The way I fixed it was to filter out worlds that have no sky.  Since the Tardis dimensions do not have sky I don't hook.  If you can get Dark's permission for me to the see the WorldProvider code it may give me ideas on what went wrong.  My reason is that I may add further features that require the provider shim and I want to make sure that my current approach is still sound.

**Comment by FoxPotato** [comment]
I don't think it's in the WorldProvider tho, I'm not sure (I'm checking it out now) but there's a function called isTardisWorld() which returns true if the WorldProvider is an instance of TardisWorldProvider. 

Can't seem to find a connection between that function and the rendering/registring of the control hits though.

**Comment by OreCruncher** [comment]
That could be it.  Reason I say that is I fixed a bug recently related to world background music.  The internal Minecraft logic was testing the WorldProvider instance type rather than checking the dimension ID for the Nether or The End.  Result was since my shim was in place those checks would fail thus no dimension background music.

**Comment by FoxPotato** [comment]
Like i said, I can't find any relation between the isTardisWorld and the control rendering. But this does seem to be the only logical thing that could be it.
Oh well, if it works it works ey 

(Let's hope it doesn't break when the update with the new WorldProvider and SkyRenderer gets added :P)

**Comment by OreCruncher** [comment]
Well, if the provider will have a sky it will break again because I will want to hook it.  Have to have darkened clouds and sky based off weather intensity. :)  Do you know when this update will happen?

**Comment by FoxPotato** [comment]
As soon as dark merges my branch :P 
And it won't have clouds anyway, it will be space.
And TARDIS dimensions don't have rain, so no need for darkened clouds :P

**Comment by OreCruncher** [comment]
As long as your provider sets hasNoSky to true we should be good.  Of course, there may be reasons for you to set to false.  Another thing I could do is put additional filtering logic in my mod by checking the dimension name.  Assuming the name of these dimensions are predictable and fairly unique (like Tardis42 or some such) it should hold.

**Comment by FoxPotato** [comment]
Well they're saved in a folder called tardis. And getDimensionName returns "Tardis Interior".
To me that seems like enough data to filter out the TARDIS dimensions :P

**Comment by DarkholmeTenk** [comment]
@FoxPotato Helper.isTardisWorld.  I don't consider that my bug because if you're overriding my code then that's your responsibility. Report it to them.

**Comment by OreCruncher** [comment]
To be clear it's not overwriting code.  Your provider is there and still active.  The shim aggregates your provider to provide additional services.

**Comment by FoxPotato** [comment]
It's indeed not overwriting the code, but it's still your bug :P

**Comment by OreCruncher** [comment]
lol - I understand.  I guess the reason I am being picky about this is because I could have handled this feature a different way.  In the first implementation I used ASM to hook the WorldProvider routines, and that version literally replaces/overwrites code. When dealing with modded Minecraft such distinctions can be important.
