### ISSUE TITLE
[BUG] netherrrrr

### ISSUE THREAD

**Issue by FoxPotato** [DarkholmeTenk/TardisModIssues#56]
Well, I'm on top of the nether. above the bedrock. might wanna fix that ;p

**Comment by DarkholmeTenk** [comment]
Not generalizable; no way to tell where the top of a dimension is for all dimensions. For some dimensions its 255, for some it's 128.
It's technically a valid location? Good place to hide a base too :P
Unsure whether or not to "fix"

**Comment by FoxPotato** [comment]
hmm good point. can't you like have a check, something like "when in nether, y => 128" and then remove the TARDIS or stop them from leaving.
the top of the nether is something you shouldn't be able to reach technically :p 
(But it really is a cool place to hide a base lol)

**Comment by DarkholmeTenk** [comment]
I could add it for 1 dimension, but then if another mod has the same thing, I'd have to add it for that dimension, etc; there could be a mod which expands the nether to the full height at which point it's not valid with that mod, etc

**Comment by FoxPotato** [comment]
you could make that mod yourself and add it to darcore :p 
I've seen plenty of coremods which change world generation.

**Comment by TorkSlanter** [comment]
You don't land on the top of the nether, you land on "The Lost Moon of Poosh". A barren piece of rock hader than diamonds and smooth as a baby's bottom.
Just so happens to contain species similar to those of Hell

**Comment by FoxPotato** [comment]
How could you land on the lost moon of poosh. It's lost.

well not anymore now i think about it, but it's now just the moon of poosh.

**Comment by spannerman79** [comment]
Personally no, have it as a config option.
For those that run a server (like me) we prefer to have the options to change ourselves.  For example I can set the max height for a specific DIM in the tardis config file and then any tardis won't rematerialize above/below that point.

For users that don't know how to setup a server (eg LAN players) they can do what they want.

**Comment by FoxPotato** [comment]
or have a config like the blacklisted dimensions.
make a whitelist for dimensions that only go up to 128.
and then the default is 255

**Comment by Soyaro666** [comment]
it can be generalized. usually if there is a top layer like in the nether it's made of Bedrock. so if the Block below the Tardis is Bedrock and the coordinates are y > 3 (as example) the Tardis would know there's a Problem. I would lock the exit door in such a case to prevent Players running around on top of the Nether and similar Dimensions. (yes, I would allow a Tardis to spawn because it could be used to resque players that got stuck in such a situation)

Sidefact: With Thaumic Tinkerer there is a Bedrock Dimension added that shouldn't be accessable without the awakened Ichorium pickaxe - that pickaxe is the only Item that can open the Portal and without that pickaxe you can't do anything in that Dimension. so with my suggestion you wouldn't just fix this so called bug but prevent incompatibilities with at least one other mod too.

aditionally I'd like to prevent the Tardis to enter Worlds that haven't been entered by players on other ways (if there's not already a way to check this i guess it would be too much work but you may get my Idea: with a Tardis you could enter the End, the Nether or other Dimensions added by Mods without ever opening the regular Portal)

**Comment by FoxPotato** [comment]
There is a blacklist option in the config, so that's easily fixed ;-)

**Comment by Soyaro666** [comment]
ah, sorry. didn't realize your message before editing. or did you mean the suggestion with the previously endered dimensions? that could be done by hand but an automation would be nice

**Comment by DarkholmeTenk** [comment]
What if I have an awakened ichorium pickaxe and want to go to the bedrock dimension in my tardis?

Also, there's absolutely no way to check if an arbitrary world has ever been visited without constantly going "Is there a player in this world?". For the vanilla worlds, you could override the portal blocks, but doing that for every mod isn't feasible. Alternatively, you could keep checking if a player is in every world, but that's slow and really inefficient.

**Comment by Soyaro666** [comment]
in that case my "if" is true so it's too much work to think further. what about my other two suggestions? ;-)

**Comment by FoxPotato** [comment]
"as final suggestion there could be a variable in a config file where you could set the highest allowed spawnpoint of a Tardis (with 0 it should pull the maximum building height)" this was already considered but some dimensions use 128 as the max and other 265 so that wouldn't work

**Comment by Soyaro666** [comment]
thats the reason for my first suggestion. but the third suggestion was to ease Darkholme by outsorcing this problem to the admins ;-)
