### ISSUE TITLE
crash on server start with all new versions (dark 257 and tardis 357) (updated dark to 259 and it still crashes)

### ISSUE THREAD

**Issue by Aaronstar-McClure** [DarkholmeTenk/TardisModIssues#589]
https://hastebin.com/vabuyogipo.sql

**Comment by Aaronstar-McClure** [comment]
updated dark and it still crashes

**Comment by DarkholmeTenk** [comment]
Try going back 1 version of TM

**Comment by Aaronstar-McClure** [comment]
still crashes https://hastebin.com/fupolicabi.sql

**Comment by FoxPotato** [comment]
perhaps also go back 1 version of darkcore, iirc the latest versions don't actually play nice together

**Comment by shadowbolt79** [comment]
I believe I've found the source of this particular crash.

https://github.com/DarkholmeTenk/TardisMod/blob/7cb19d2791ada379f9d16c7401d304a9e614525a/src/main/java/tardis/common/blocks/AdvancedLabBlock.java

AbstractBlockRenderer getRenderer()

is an @Override for: 

https://github.com/DarkholmeTenk/Darkcore/blob/master/src/main/java/io/darkcraft/darkcore/mod/abstracts/AbstractBlockContainer.java

which  is protected by a @SideOnly(side.client).

When the TARDIS mod goes and looks for this other function to override, it finds none because it's not there. I BELIEVE (I have not tested this) You need to add @SideOnly to the new getRenderer()

**Comment by shadowbolt79** [comment]
@Aaronstar-McClure Try going back to tardismod 355. That was before this change was made.
