### ISSUE TITLE
Incompatibility with DragonAPI

### ISSUE THREAD

**Issue by comus777** [DarkholmeTenk/TardisModIssues#597]
Just attempted to install your TARDIS mod, and it seems to be incompatible with DragonAPI

Crashlog: 
http://pastebin.com/EwN8CDLe

Hope you do something to resolve it so that I can use this mod in conjunction with the rest that I use.

**Comment by shadowbolt79** [comment]
`Caused by: appeng.api.exceptions.CoreInaccessibleException: AE2 API tried to access the appeng.core.Api class, without it being declared.
    at appeng.api.AEApi.<clinit>(AEApi.java:56)`

problem is caused by applied energistics 2 compatability. As weird as this sounds, try adding applied energistics 2.

**Comment by comus777** [comment]
Wow.... it actually works. Thanks I guess? 

Weirdest case of lacking a dependency I've ever seen.

**Comment by shadowbolt79** [comment]
Likely DragonAPI added a copy of the API for AE2, and the TardisMod detected that, thinking AE2 was actually installed. It all depends on what class they are checking for.

**Comment by DarkholmeTenk** [comment]
nope, this is a case that dragonapi breaks the part of forge which removes code for mods which don't exist.

I've raised it with reika and got the response that it's a "forge bug"

**Comment by SvEgiiVEteR** [comment]
@DarkholmeTenk 
And how to fix it? With DragonAPI 1.7.10 V17c too Crash
Seems to need a version of appliedenergistics2-rv3
it does not work with TARDIS :(

**Comment by AlienXtream** [comment]
dragonAPI & all of reika's mods are incompatible with a of things. this isn't a TM issue, its a DragonAPI issue.

**Comment by SvEgiiVEteR** [comment]
@AlienXtream 
no. 
DragonAPI 1.7.10 V12 works great with this mod.
In the TARDIS **API** appliedenergistics2-**rv2**
In DragonAPI 1.7.10 V17c **API** appliedenergistics2-**rv3**
TARDIS does not start with appliedenergistics2-**rv3**
TARDIS is started with appliedenergistics2-**rv2**


DragonAPI 1.7.10 V17c + appliedenergistics2-**rv3** also perfectly run BUT WITHOUT TARDIS - because of the old API
Or how do I TARDIS + appliedenergistics2-**rv2** + DragonAPI 1.7.10 V12 work well
DragonAPI 1.7.10 V17c does not work with **API** appliedenergistics2-**rv2** but with AE2**rv2** running TARDIS

**Comment by AlienXtream** [comment]
still DragonAPI. we do not support reika's mods due to their instability. if you get them to work well, good for you. if not too bad. its not because they are bad/unpopular, its just because of how reika handles his dependencies and other mods API's it makes things very touchy with regard to updates. in summary (and in caps for clarity, not yelling)

DARK CORE AND IS ASSOCIATED MODS DO NOT ACTIVELY SUPPORT DRAGONAPI AND ITS DEPENDANTS

**Comment by SvEgiiVEteR** [comment]
What does DragonAPI have to do with this? I have already written above the PROBLEM In the API appliedenergistics2-rv3
TARDIS does not work with AE2rv3 and reika's mods is not involved here ... it's just a consequence

**Comment by DarkholmeTenk** [comment]
TardisMod has definitely worked with AE2rv3 in the past and nothing related to that has changed. There are known classpath issues with the most recent jenkins builds though.

However, if you have DragonAPI it is known to break (or cause a forge bug, if you ask reika, which breaks) the code which forge uses to strip the ae2 apis.

If you can prove a bug with just TM and AE2rv3 with DragonAPI not installed at all, then that should be raised as a new ticket.

**Comment by SvEgiiVEteR** [comment]
@DarkholmeTenk Strange ... I have TardisMod when not working with RV3. Now I understand what's the matter. Thank you. Create a new issue
but AE2rv2 with DragonAPI 12 + TardisMod all ok
