### ISSUE TITLE
1.7.10 tardis mod (levels)

### ISSUE THREAD

**Issue by Josh65-2201** [DarkholmeTenk/TardisModIssues#602]
at random time the tardis will reset to 0 and will remove upgrades from the engine

**Comment by AlienXtream** [comment]
odd. during hundreds of hours using the mod on a heavily modded instance iv'e never had this issue... can you provide more info?

**Comment by Josh65-2201** [comment]
It happens randomly when i leave the game or tardis but i have try saving a copy of the levels file and replace it whene it happens and that works so far

**Comment by AlienXtream** [comment]
im glad you have a workaround but this is still a bug and it needs to be fixed asap. that cant happen unless we know WHY its resetting periodically, and given you are the only case i can remember of this you have to help us track it down 
:)

**Comment by Josh65-2201** [comment]
Ok

**Comment by Josh65-2201** [comment]
it seems it resets the levels when i install another mod

**Comment by Portalboy** [comment]
I just encountered this as well on a 1.7.10 server. Logged on today and TARDIS is level 0. The server is managed by me and running off a local box so I know the world file or mod data wasn't tweaked.

**Comment by kryzeth** [comment]
Me and my friend have also encountered this multiple times. It hadn't happened for the longest time, but then one session, we found the tardis level and custom permissions had been reset. Ever since then, it's been happening more and more often; now almost every time we start up the game, the tardis is back to 0 and we have to cheat it back up to the previous level with commands.

If possible, that workaround might really help, but we can't find any levels file in the save?

For reference, we are playing Project Ozone 2 Reloaded v2.2.7, using tardis mod v1.7.10-0.994-124-DS (with a few reika mods added in)

**Comment by Josh65-2201** [comment]
It will be in the config folder and find the folder called tardis mod

**Comment by Ironsidemaster** [comment]
this is happening for me too and i dont know why

**Comment by Soyaro666** [comment]
So, let's bring some system into the search for a solution. Could you provide a list of mods you're using while this error occurs? kryzeth did pretty much that by naming project ozone 2. I'd like to compare the mod lists...
Are there any hints in the logfiles maybe? If you could find logs around this error (i.e. from saving before and from loading after you lost the levels) there could be a hint.

**Comment by Josh65-2201** [comment]
my old ones got deleted and it hasn't happened again yet.
