### ISSUE TITLE
colorable stuffs.

### ISSUE THREAD

**Issue by TylorBane** [DarkholmeTenk/TardisModIssues#606]
just out of curiosity, i was wondering why blocks like the slabs and stairs still arn't color-able? is there some kind of rendering issue that would make it look bad if this was done? I'm just don't like that i have to leave those ugly white blocks all over my tardis :stuck_out_tongue: anyway, just a question, and longing for a matching tardis

**Comment by AlienXtream** [comment]
its due to block id's. the different colored wall block each have the same item ID with different meta data (kinda like how people in the same family have different names except instead of "john smith" its "smith:john"), this is how vanilla wool blocks work too. problem is its also what slabs use to know if they are top or bottom (as well as stairs and their rotation). while it IS possible to have them color able it would require dark to use 32 block id's instead of 2 and in modded MC the block id limit is something that has to be considered. if you are looking for a solution i can suggest carpenters blocks. the craftable interior blocks "(c)" CAN be picked up with silk touch (this is actually a bug so the icons all look the same :P) and placed in carpenters blocks, though just be aware that i have had some MINOR graphical inconsistencies in the past doing this (nothing game breaking, just colors not as expected). if you decide to go that route just dont bother saving it as as a schema file as the carpenters blocks lose some of their data, leaving random items in the CB render slot (i tried it once and instead of a block in the stairs i had a sapling :D). this happens because when modded MC is loading it somehow decides what blocks belong to what ID or something like that and if you try and load it into an instance of MC that has different mods or a different number of items the ID get shuffled around for some reason. this is accounted for in MC with placed tiles and blocks but not ones in inventories so the ones in containers dont get shuffled with the list and end up changing. thats how i understand it (probably a lot more to it but you could likely write an essay on the topic :P)

hope that answers your question (and all the questions that might pop up later on) and helps you better understand TM :)

**Comment by TylorBane** [comment]
32 block ids? couldnt you just add the 16 color vairiants as more meta datas? say, have all of white be the first set then orange and so on, in the same ordered list that minecraft uses? not to say that your idea is null, but it sounds possible enough, it would just have to have what... 256 different "metadata"s? it doesn't seem that hard i don't think, just a bit of time and effort to get it to work right. Though i dont know how many metadata vertions of a single block is actually posible in minecrafts base code so... Anyway, those are just my thoughts, :man_shrugging: i just hate the white blocks under the console and in the super big room is all and thought i'd share my idea

**Comment by AlienXtream** [comment]
i feel your artistic pain brethren :P. while i too am unsure of the inner workings of meta data i know of at least ONE perfectly good and valid reason. Dark is evil (DONT play a rts game with him if you have any desire to win O.o he toys with you like a cat with a mouse... and not one of those cat video cats you see snuggling a bunny.... :P) joking aside the point of it being a lot of effort is why dark HASN'T made it happen. there would be so much reworking needed it would be nonviable, not to mention that the changes would almost CERTAINLY break any existing builds that contained either slabs or stairs. in conclusion, CAN it be done? definitely; is dark going to do it? most probably not ;/ 

im in no way trying to discourage your creativity. quite the contrary, i hope that in light of the facts presented, you rise above this challenge and find a way to work WITH the confines of our cuboidal playground. wow that got deep :/ lol

**Comment by TylorBane** [comment]
"not to mention that the changes would almost CERTAINLY break any existing builds that contained either slabs or stairs." not necessarily... the white stairs and slabs are already set up correctly right? start adding orange right after and nothing that currently exists will break :+1: if i knew how to java i'd do it myself and hand him the code but, :man_shrugging: i do not... anyway, there are ways to implement it without problems with too many blocks or breaking currently made schemas it would just take time. anyway, the conversation was nice.

Oh and about meta data? i now know that you can even go past 256, as decocraft has a total meta data value of over 1400

**Comment by AlienXtream** [comment]
actually, thinking about it, tools use large metadata too... anyway, if this topic is done mind closing it too help unclutter the issues tab :P

**Comment by TylorBane** [comment]
Yeah, it's done. I'll close it but if your close friends with dark or if you can talk to him through IM or something, I'd like a moment to pitch my idea directly with more detail than I had here if that would be possible.

**Comment by AlienXtream** [comment]
dont worry about that, dark is well aware of all the discussions that happen here (even if he doesn't reply to them all). if you REALLY want colored slabs then if you have any friends who are proficient in JAVA i suggest you give them a poke as the mod is open source for addon purposes. an easy alternative i can suggest is to use some sort of mod maker to create the 16 slab versions and apply the textures to them (i think dark sets the colour of the tardis blocks within the code rather than with 16 textures as i haven't seen any coloured textures in the files)
