### ISSUE TITLE
[suggestions] ADMIN Tardis Key

### ISSUE THREAD

**Issue by Aaronstar-McClure** [DarkholmeTenk/TardisModIssues#615]
a creative only tardis key that allows summoning or transmatting to any tardis. good if someones tardis bugs out, or gets lost.

**Comment by FoxPotato** [comment]
there's a command, /ttp which allows you to go to any (tardis) dimensions. Don't know about summoning someone else's tardis tho, that might be a good command if it doesn't exist already. Been a while since I've actually played minecraft in general :P

EDIT: a reliable source just informed me that there's a t(ardis)summon command
