### ISSUE TITLE
I want to continue development

### ISSUE THREAD

**Issue by SolsticeLeaf** [DarkholmeTenk/TardisModIssues#659]
Hi! My name is Alexander. I see that you have long abandoned the development of Minecraft Tardis Mod. Last supported version: 1.7.10. My friends and I would like to continue your business, but for this I need your consent.
I apologize for my English. Thank you for your understanding =)

**Comment by AlienXtream** [comment]
the mod is no longer maintained or even really usable. its dead. even if you were to update its likely 80% or more of the code would need to be rewritten to support changes in both forge and minecraft since 1.7.10. basically the only salvageable thing would be the textures. look to other similar mods or feel free to create your own.
