### ISSUE TITLE
[ENHANCE]More storage scaling

### ISSUE THREAD

**Issue by Durpady** [DarkholmeTenk/TardisModIssues#73]
At present, RF capacity scales with TARDIS level.  Why not do that for items, fluids and Essentia?

**Comment by FoxPotato** [comment]
It does, i thought

**Comment by DarkholmeTenk** [comment]
because RF is just stored as an int, i.e. the amount of energy stored. Whereas items, fluids and essentia have to be stored as an array of things, e.g. a collection of 30 items. Changing the RF limit is just "make this number bigger", whereas changing the number of items requires making a bigger array and copying the entire contents of the old array over, which means not only are we now using a decent bit more memory to store things, we've had to spend a lot of time copying items.

Going from 30 items to 60 requires copying 30 items, going from 60 to 90 requires copying 60 items, say you get to level 30, that means you've now got 900 items and we've had to copy in total: 870 + 840 + 810 etc items to give somewhere near 14000 item copies.

It's a nice idea, but it's not nice on performance and things.

**Comment by Durpady** [comment]
Then perhaps you could delay the capacity increase until its current capacity is empty?  If I understand this correctly, that should mean that you won't have to copy anything.

**Comment by DarkholmeTenk** [comment]
It still means using more memory though :P

**Comment by Durpady** [comment]
I have another idea for a workaround, but it revolves around there being a maximum TARDIS level.  The maximum amount of inventory spaces would be "loaded" from the start, but they'd be "locked" until the TARDIS levels up.

**Comment by FoxPotato** [comment]
Or just create an ME system in one of the corridors. :p

**Comment by DarkholmeTenk** [comment]
Gonna close this; the cable interfaces are (in my mind) supposed to be for getting stuff from one location to another with a buffer, not to act as a storage system.
