### ISSUE TITLE
[ENHANCE] Chameleon Circuit

### ISSUE THREAD

**Issue by micmou** [DarkholmeTenk/TardisModIssues#80]
The Chamelon Circuit will allow us to disguise as objects that we define in game either as a machine from another mod or copy an area say I build a chair out of trap doors and allow us to copy it or maybe an ingame model editor. and obvious pre-done models IE

 piano, clock, pillar, diffrent tardis exteriors.

Also a larger tardis exterior

**Comment by FoxPotato** [comment]
Why does everyone want a larger exterior? Am I the only one who likes it D:

**Comment by DarkholmeTenk** [comment]
The exterior's gonna stay at 1x2x1 because it makes the code relatively simple; allowing for multiple sizes would massively change the flight code especially the collision detection.

The idea of other models is definitely gonna happen at some point.

The ability to copy things from ingame isn't gonna happen though, that's way too much work and I don't think it'd be as cool as it sounds.

**Comment by Durpady** [comment]
It'd be nice if the TARDIS could turn into the small cube ("siege mode") seen in Flatline.  Flight code shouldn't be an issue since I'm pretty sure the TARDIS can't fly in siege mode anyway.

The only question is, should it be an unbreakable block, or should it be able to drop as an item?  If the latter though, its item form should still be indestructible by fire/cactus/explosions and despawning (keeping other mods from deleting it from an inventory, like Buildcraft Void Pipes, or Railcraft Void Chests, might be more trouble than it's worth).

**Comment by FoxPotato** [comment]
wow, siege mod sounds actually quite cool. lmao.
Undestructable block sounds too much of a pain tho. you could block people their houses and stuff.
But also I think it's impossible to have it not destroyed by mods? And there is always the NEI clearing inventory :/

**Comment by laz2727** [comment]
Make it a small entity.

**Comment by FoxPotato** [comment]
But then you wouldn't be able to pick up the thing.
which would probably be better bc else it'll be really hard for Dark to track where the TARDIS should grow again. And now i think about it, it would probably be really hard to do it in the first place lmao

**Comment by Durpady** [comment]
Unless it remains an unbreakable block.

**Comment by FoxPotato** [comment]
Yeah, but then again you get the problem of being able to fuck people over by blocking stuff.

**Comment by micmou** [comment]
@FoxPotato Not necessarily needed to make the exterior indestructible as you can re build it with a tardis key charge with huon energy :P

**Comment by FoxPotato** [comment]
Yeah but, How would you re build the TARDIS while inside of it. 
It has to be enabled from inside of the TARDIS and prevents people from entering and leaving. :/

**Comment by micmou** [comment]
@FoxPotato  Umm from the inside you have direct control over the chamelon circuits and would be able to reconstruct the exterior with Block-Transfer Mass as the Exterior is just a shell that control Physical access in-game as well as in real life and you already know the exterior rebuilding bit.

**Comment by FoxPotato** [comment]
oh fudge, i meant outside of it.
sorry, it was like 1am and stuff for me :p 
a key wouldn't work bc that doesn't work on the inside.

**Comment by Durpady** [comment]
One unbreakable block isn't going to impede much.  Players can just build/mine around it.  And remember, while it's in siege mode, the owner (and any other players) can't leave.

**Comment by FoxPotato** [comment]
I know. that's what I said.
And believe me, being able to just place an ubreakable block in someone's house is quite annoying.
MAybe it could just be an entity that can be pushed around.

gotta watch out with having it respawn then tho, seeing as you could push it kinda into a block and then glitch out and stuff. I can already think of ways to break the game :p

**Comment by micmou** [comment]
Well in the show it is quite light and you can't grief proof everything unfortunately trust me servers have tried

**Comment by FoxPotato** [comment]
You can, and should, always try. Especially when making mods.
Now I think about it, what would be the use of this mode ._.

**Comment by micmou** [comment]
well umm let your frenemy carry you into the enemies base than rematerialize as a tardis and let all the peeps out??? Infiltration and deception once chamelon circuit is installed allow it to look like a pumbkin block enemy picks up places in base tada bypass all the defenses

**Comment by FoxPotato** [comment]
Well there are 2 problems with that message,
1. I was talking about the siege mode, where it becomes a little block and no one can enter nor leave.
2. he said the TARDIS will stay a 1x2 block so that's not gonna happen

**Comment by micmou** [comment]
Actually he has confirmed the chamelon circuit as a thing somewhere can't remeber where he could also make it a microblock :P

And I am aware that you were talking about siege mode

**Comment by FoxPotato** [comment]
He said he was gonna try to add more exterior models. but the exterior had to stay 1x2.

**Comment by micmou** [comment]
The reason for this is simplicity with a 1x1 model or the microblock entity it wouldn't be that hard

**Comment by FoxPotato** [comment]
"

The exterior's gonna stay at 1x2x1 because it makes the code relatively simple; allowing for multiple sizes would massively change the flight code especially the collision detection.

The idea of other models is definitely gonna happen at some point.

The ability to copy things from ingame isn't gonna happen though, that's way too much work and I don't think it'd be as cool as it sounds.
"

He could always disable the ability to fly when in chameleon mode, or that it resets when you take off.
idk, idek if that's the problem with the code.

**Comment by micmou** [comment]
well in siege mode there is no flying...

**Comment by FoxPotato** [comment]
this time I was talking about the chameleon circuit.

**Comment by DarkholmeTenk** [comment]
Siege mode != chameleon circuit.
Chameleon circuit is definitely going to be implemented (and exteriors are all going to be 1x2x1).
Siege mode is still a maybe.

**Comment by FoxPotato** [comment]
okey dokey,
Any idea what the options will be yet?

**Comment by DarkholmeTenk** [comment]
Basic Chameleon circuit implemented in DS branch.
